language: groovy

sudo: false

jdk:
    - oraclejdk7

before_install:
    - mkdir -p ~/.m2
    - git clone --depth 1 git://github.com/thehyve/transmart-travis.git ~/ts-travis
    - source ~/ts-travis/init.sh
    - source ~/ts-travis/grails_inline.sh
    - source ~/ts-travis/maven_dep.sh
    - mkdir -p ~/.grails/transmartConfig
    - cp .travis.BuildConfig.groovy ~/.grails/transmartConfig/BuildConfig.groovy

install:
    - build_maven_dep $(travis_get_owner)/${PREFIX}transmart-core-api master core-api
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}transmart-core-db "$DEFAULT_BRANCH" core-db . transmart-core-db-tests
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}Rmodules "$DEFAULT_BRANCH" Rmodules
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}transmart-gwas "$DEFAULT_BRANCH" transmart-gwas
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}folder-management "$DEFAULT_BRANCH" folder-management
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}transmart-extensions "$DEFAULT_BRANCH" transmart-extensions transmart-java search-domain biomart-domain
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}transmart-rest-api "$DEFAULT_BRANCH" transmart-rest-api
    - make_inline_grails_dep $(travis_get_owner)/${PREFIX}SmartR "$DEFAULT_BRANCH" smartR

script:
    - grails refresh-dependencies --non-interactive
    - grails test-app --non-interactive --stacktrace
    - grails war

notifications:
    on_success: change
    on_failure: always
